### ISSUE TITLE
Move to Backdrop contrib repo?

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/viewsicalexport#1]
I've recently installed this module, it matches my use case very well. Have you considered to move it to the [Backdrop contrib repository](https://github.com/backdrop-contrib) and even to make a release? I'd volunteer to write some basic instructions for the README.

(I'm not sure if moving the module to Backdrop contrib should be discussed with the maintainer of [Date iCal](https://github.com/backdrop-contrib/date_ical).)

**Comment by indigoxela** [comment]
> Have you considered to move it to the Backdrop contrib repository and even to make a release?

I did, but wanted to wait for at least a second person, who finds it useful.

> I'm not sure if moving the module to Backdrop contrib should be discussed with the maintainer of Date iCal

He knows, that my module exists: https://github.com/backdrop-contrib/date_ical/issues/2

First I tried to help out with getting his port up an running.
But as his port has at least one showstopper issue, which is hard to fix, I wrote my own (lightweight) solution.

**Comment by olafgrabienski** [comment]
> wanted to wait for at least a second person, who finds it useful

So here I am !-), and I also like the lightweight approach.

Are you already a member of the Backdrop contrib group? If not, on https://github.com/backdrop-ops/contrib you'll find instructions how to apply.

**Comment by indigoxela** [comment]
> Are you already a member of the Backdrop contrib group?

Not yet, but maybe soon: https://github.com/backdrop-ops/contrib/issues/350
