### ISSUE TITLE
Clarify "Attach entity url" option

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/viewsicalexport#2]
In the settings of the row style *iCal Fields*, there is the "Attach entity url" option, with the description: "Attach the entity url to VEVENTS, so the calendar item has a link to your event".

I can see the URL in the preview of the view (e.g. `ATTACH:https://example.org/MY-EVENT`) but my calendar items don't show that link, or I don't find it. Where is the link supposed to be displayed usually?

Is it maybe an issue with certain calendar clients or specific calendar app settings? So far tested with the Calendar apps of Mac OS X and iOS.

**Comment by indigoxela** [comment]
Yes, unfortunately it's up to the clients, where and how they show "ATTACH".

In Outlook it's visible, Thunderbird shows it under "Attachments" tab (needs a click)...
Not sure, where Mac clients put these.

**Comment by olafgrabienski** [comment]
Thanks for your feedback! I'll try to find out if and where Mac clients show `ATTACH` and will report back here.

**Comment by olafgrabienski** [comment]
I haven't had any time so far to find out how Mac OS or iOS calendar apps handle ATTACH. It's however not that important for me, so I'm going to close the issue.
