### ISSUE TITLE
Undefined property: BackdropDateTime::$timezone

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/viewsicalexport#3]
I see a lot of notices on a site where I'm using Views iCal Export:

> Notice: Undefined property: BackdropDateTime::$timezone in ViewsicalexportPluginStyleIcalFeed->dateObjectToString() (line 33 of /(...)viewsicalexport/views/viewsicalexport_plugin_style_ical_feed.inc).

(Didn't investigate further so far.)

**Comment by indigoxela** [comment]
> Didn't investigate further so far

Please do. ;)

The date field on your content type - what timezone settings does it have?
It's either:

- Website
- Date
- User
- UTC
- No conversion

**Comment by olafgrabienski** [comment]
The setting on the date field is "Site's time zone".

**Comment by indigoxela** [comment]
> The setting on the date field is "Site's time zone"

OK, shouldn't have been a problem anyway.

As the problem occurs in line 33 of viewsicalexport_plugin_style_ical_feed.inc, I suppose your'e using date_all_day module. Is that correct?

How many event nodes do you have currently?
Does the ical feed render anyway?
What do you see on your views UI edit page, when clicking on "Update preview" (Vorschau aktualisieren)?

**Comment by olafgrabienski** [comment]
Thanks @indigoxela!

> I suppose your'e using date_all_day module

Yes, that's the case, and I've enabled the "Display all day checkbox" on the date field.

> How many event nodes do you have currently?

There are about 220 event nodes altogether. The view shows however only 20 future events (Filter: Is greater than or equal to 'now').

> Does the ical feed render anyway?

Yes, it does. Many people don't have any issues to add the feed to their calendar, and the calendar is displaying the events. (Some told me they weren't able to add the calendar to their device, but that might be a separate issue, maybe device or client related.)

> What do you see on your views UI edit page, when clicking on "Update preview"?

I'm pasting the preview of only *one* event as an example. Let me know, if more information would be helpful.

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Backdrop Views Ical Export
METHOD:PUBLISH
X-WR-CALNAME;VALUE=TEXT:AWV-Termine
BEGIN:VEVENT
UID:events.367.field_termin_datum.0@EXAMPLE.ORG
DTSTAMP:20190902T161225Z
SUMMARY:MY-EVENT-1
DTSTART:20190907T160000Z
DTEND:20190907T160001Z
LOCATION:MY-LOCATION
LAST-MODIFIED:20181210T093121Z
CREATED:20181210T093121Z
ATTACH:https://EXAMPLE.ORG/MY-EVENT-1
END:VEVENT
END:VCALENDAR
```

**Comment by indigoxela** [comment]
Many thanks for your info. I was able to reproduce it now.

A bugfix has been committed, but not released yet.

https://github.com/backdrop-contrib/viewsicalexport/commit/70abb04a376f2d45e6cb4691bff42617741476f6

Can you verify, this fixes the notices for you? (If you dare to test it.)

**Comment by olafgrabienski** [comment]
> Can you verify, this fixes the notices for you?

Sure, I'll give it a try tomorrow.

**Comment by olafgrabienski** [comment]
@indigoxela I've applied the fix to a dev site, and it looks like the notices are gone. To test it, I made sure that there is an upcoming all day event on the website and refreshed the events in the calendar client. After that, I didn't see new notices in the DBlog.

**Comment by indigoxela** [comment]
Cool, many thanks for reporting and testing.

A new release is available: https://github.com/backdrop-contrib/viewsicalexport/releases/tag/1.x-1.0.1

**Comment by olafgrabienski** [comment]
Thank *you* for the fix and the new release. I've updated the site, looks good!

**Comment by olafgrabienski** [comment]
Strange, I get the same PHP notice again, on the same site where it appeared three years ago:

> Notice: Undefined property: BackdropDateTime::$timezone in ViewsicalexportPluginStyleIcalFeed->dateObjectToString() (line 35 of /(...)viewsicalexport/views/viewsicalexport_plugin_style_ical_feed.inc).

I'm pretty sure the notices re-appeared only in the last weeks. In that period, I updated Views iCal Export to version 1.x-1.2.1, and I also changed the PHP version from 7.0 or so to 7.4.

@indigoxela Should I reopen this issue, or do you prefer a new one?

**Comment by indigoxela** [comment]
> Should I reopen this issue, or do you prefer a new one?

@olafgrabienski I'd actually prefer a new one, this one here's just too old. And ideally with steps to reproduce.
