### ISSUE TITLE
Undefined property: BackdropDateTime::$timezone (Follow-up)

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/viewsicalexport#5]
This is a follow-up issue to https://github.com/backdrop-contrib/viewsicalexport/issues/3 which was fixed in September 2019.

After the issue was fixed and the site in question ran fine, I recently noticed the issue again, on the same site:

> Notice: Undefined property: BackdropDateTime::$timezone in ViewsicalexportPluginStyleIcalFeed->dateObjectToString() (line 35 of /(...)viewsicalexport/views/viewsicalexport_plugin_style_ical_feed.inc).

I'm not sure when exactly the notices reappeared, but in case it helps: I recently changed the PHP version from 7.0 or so to 7.4 on the site in question. I also updated Views iCal Export to version 1.x-1.2.1, but on another site with the same module version I didn't notice the issue so far.

Steps to reproduce:

- Build an event-like content type with a Date field, enable the "Display all day checkbox " provided by the "Date All Day" contributed module.
- Create a view of events, and add a block display.
- Add an iCal Feed display, and attach it to the block.
- Place the block in a layout, so that the feed is on a page.
- Go to the page and subscribe to the iCal feed (to make sure it works).
- Subscribe to the iCal feed / add it to your local calendar application.
- Verify that your app contacts the feed from the website, by checking if the app displays events from there.
- Have a look at the DBlog. There are many of the notices mentioned above.

~~Not sure if that helps. Which kind of information would be more helpful?~~

edit: I've added the steps "Subscribe to the iCal feed ..." and "Verify that your app contacts the feed ...".

**Comment by olafgrabienski** [comment]
When I click on "Update preview" on the Views edit page, I see the following text (pasting only one event as example):

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Backdrop Views Ical Export
METHOD:PUBLISH
X-WR-CALNAME;VALUE=TEXT:MY-EVENTS
BEGIN:VEVENT
UID:events.734.field_termin_datum.0EXAMPLE.ORG
DTSTAMP:20230414T161204Z
SUMMARY:MY-EVENT
DTSTART;VALUE=DATE:20230421
DTEND;VALUE=DATE:20230424
LOCATION:MY-LOCATION
LAST-MODIFIED:20230330T152523Z
CREATED:20221127T112343Z
ATTACH:https://EXAMPLE.ORG/PATH-TO-EVENT
END:VEVENT
(...)
END:VCALENDAR
```

**Comment by indigoxela** [comment]
Yes, I can reproduce. Many thanks for reporting.

A [PR](https://github.com/backdrop-contrib/viewsicalexport/pull/6) is available for testing. Be warned, it's Friday early evening code. :grin:

**Comment by olafgrabienski** [comment]
Wow, that was quick, thanks a lot! (I'm not that quick, will test the PR in the next days.)

**Comment by olafgrabienski** [comment]
@indigoxela, thanks again! I've tested the PR, and it seems to work fine:

Without the PR, I can trigger the reported notices by disabling and re-enabling the iCal feed in my local calendar app. After applying the PR to a test site, the notices don't appear in that situation.

**Comment by indigoxela** [comment]
@olafgrabienski that's great news. Many thanks for testing. I guess, a new release makes sense, many people use newer PHP versions nowadays.
